// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516144526_AddAiChats")]
    partial class AddAiChats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.AiChat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("AiChats");
                });

            modelBuilder.Entity("Core.Entities.AiMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("AiMessages");
                });

            modelBuilder.Entity("Core.Entities.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long>("SportsmanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TrainingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SportsmanId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Core.Entities.Broadcast", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Broadcasts");
                });

            modelBuilder.Entity("Core.Entities.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<TimeOnly>("BeginTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("SportHall")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Core.Entities.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PersonalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SportsmanId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("SportsmanId");

                    b.HasIndex("TeamId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Core.Entities.LocalNormative", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)");

                    b.Property<bool>("IsMoreBetter")
                        .HasColumnType("boolean");

                    b.Property<int>("Specialization")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("LocalNormatives");
                });

            modelBuilder.Entity("Core.Entities.LocalNormativeSportsman", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("LocalNormativeId")
                        .HasColumnType("bigint");

                    b.Property<double>("Result")
                        .HasColumnType("double precision");

                    b.Property<long>("SportsmanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocalNormativeId");

                    b.HasIndex("SportsmanId");

                    b.ToTable("LocalNormativeSportsmen");
                });

            modelBuilder.Entity("Core.Entities.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("HomeTeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OpponentTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("OpponentTeamName")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainerComment")
                        .HasColumnType("text");

                    b.Property<long?>("TrainingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("OpponentTeamId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Core.Entities.MatchEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsHomeTeam")
                        .HasColumnType("boolean");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("Minute")
                        .HasColumnType("integer");

                    b.Property<long?>("SportsmanId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubstituteSportsmanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("Core.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BroadcastId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BroadcastId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Core.Entities.Normative", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AgeGroup")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)");

                    b.Property<double>("GradeExcellent")
                        .HasColumnType("double precision");

                    b.Property<double>("GradeGood")
                        .HasColumnType("double precision");

                    b.Property<double>("GradeSatisfactory")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAboveYearOfStudy")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Normatives");
                });

            modelBuilder.Entity("Core.Entities.NormativeSportsman", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("NormativeId")
                        .HasColumnType("bigint");

                    b.Property<double>("Result")
                        .HasColumnType("double precision");

                    b.Property<long>("SportsmanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormativeId");

                    b.HasIndex("SportsmanId");

                    b.ToTable("NormativeSportsmen");
                });

            modelBuilder.Entity("Core.Entities.Personal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("Core.Entities.PersonalWorkout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("PersonalId")
                        .HasColumnType("bigint");

                    b.Property<long>("SportsmanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Workout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("SportsmanId");

                    b.ToTable("PersonalWorkouts");
                });

            modelBuilder.Entity("Core.Entities.PlanTraining", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Workouts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("PlanTrainings");
                });

            modelBuilder.Entity("Core.Entities.PlayerEmbedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SportsmanId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 10);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SportsmanId");

                    b.ToTable("PlayerEmbeddings");
                });

            modelBuilder.Entity("Core.Entities.Sportsman", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int>("Specialization")
                        .HasColumnType("integer");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sportsmen");
                });

            modelBuilder.Entity("Core.Entities.SportsmanGroup", b =>
                {
                    b.Property<long>("SportsmanId")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("SportsmanId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("SportsmanGroups");
                });

            modelBuilder.Entity("Core.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AgeGroup")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Core.Entities.Training", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("text");

                    b.Property<long?>("PlanTrainingId")
                        .HasColumnType("bigint");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PlanTrainingId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Core.Entities.TrainingMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccelerationCount")
                        .HasColumnType("integer");

                    b.Property<double>("AverageHDOP")
                        .HasColumnType("double precision");

                    b.Property<int>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<int>("AverageSatellites")
                        .HasColumnType("integer");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DecelerationCount")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceInSpeedZone1")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceInSpeedZone2")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceInSpeedZone3")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceInSpeedZone4")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceInSpeedZone5")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceInSpeedZone6")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceInSpeedZone7")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision");

                    b.Property<int>("ExplosiveEfforts")
                        .HasColumnType("integer");

                    b.Property<double>("HeartRateExertion")
                        .HasColumnType("double precision");

                    b.Property<int>("HighSpeedDistance")
                        .HasColumnType("integer");

                    b.Property<int>("HighSpeedEfforts")
                        .HasColumnType("integer");

                    b.Property<int>("Impacts")
                        .HasColumnType("integer");

                    b.Property<int>("LowSpeedDistance")
                        .HasColumnType("integer");

                    b.Property<double>("MaxAcceleration")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxDeceleration")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<double>("MaximumSpeed")
                        .HasColumnType("double precision");

                    b.Property<double>("MetabolicPower")
                        .HasColumnType("double precision");

                    b.Property<int>("ModerateSpeedDistance")
                        .HasColumnType("integer");

                    b.Property<double>("PlayerLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("PositionGroup")
                        .HasColumnType("text");

                    b.Property<long>("SportsmanId")
                        .HasColumnType("bigint");

                    b.Property<int>("SprintDistance")
                        .HasColumnType("integer");

                    b.Property<int>("SprintEfforts")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInHRRedZone")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInHRZone1")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInHRZone2")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInHRZone3")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInHRZone4")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInHRZone5")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInHRZone6")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInSpeedZone1")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInSpeedZone2")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInSpeedZone3")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInSpeedZone4")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInSpeedZone5")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInSpeedZone6")
                        .HasColumnType("integer");

                    b.Property<int>("TimeInSpeedZone7")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDistance")
                        .HasColumnType("integer");

                    b.Property<long>("TrainingId")
                        .HasColumnType("bigint");

                    b.Property<double>("WorkRatio")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SportsmanId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingMetrics");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.AiChat", b =>
                {
                    b.HasOne("Core.Entities.Personal", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Core.Entities.AiMessage", b =>
                {
                    b.HasOne("Core.Entities.AiChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Core.Entities.Attendance", b =>
                {
                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany()
                        .HasForeignKey("SportsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportsman");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Core.Entities.Broadcast", b =>
                {
                    b.HasOne("Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Core.Entities.Class", b =>
                {
                    b.HasOne("Core.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Entities.Group", b =>
                {
                    b.HasOne("Core.Entities.Personal", "Trainer")
                        .WithMany("Groups")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Core.Entities.Image", b =>
                {
                    b.HasOne("Core.Entities.Personal", "Personal")
                        .WithMany("Images")
                        .HasForeignKey("PersonalId");

                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany("Images")
                        .HasForeignKey("SportsmanId");

                    b.HasOne("Core.Entities.Team", "Team")
                        .WithMany("Images")
                        .HasForeignKey("TeamId");

                    b.Navigation("Personal");

                    b.Navigation("Sportsman");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Core.Entities.LocalNormativeSportsman", b =>
                {
                    b.HasOne("Core.Entities.LocalNormative", "LocalNormative")
                        .WithMany("LocalNormativeSportsmen")
                        .HasForeignKey("LocalNormativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany("LocalNormatives")
                        .HasForeignKey("SportsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalNormative");

                    b.Navigation("Sportsman");
                });

            modelBuilder.Entity("Core.Entities.Match", b =>
                {
                    b.HasOne("Core.Entities.Team", "HomeTeam")
                        .WithMany("Matches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Team", "OpponentTeam")
                        .WithMany()
                        .HasForeignKey("OpponentTeamId");

                    b.HasOne("Core.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId");

                    b.OwnsMany("Core.Entities.LineupEntry", "Lineup", b1 =>
                        {
                            b1.Property<long>("MatchId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("SportsmanId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("MatchId", "__synthesizedOrdinal");

                            b1.ToTable("Matches");

                            b1.ToJson("Lineup");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("HomeTeam");

                    b.Navigation("Lineup");

                    b.Navigation("OpponentTeam");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Core.Entities.MatchEvent", b =>
                {
                    b.HasOne("Core.Entities.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Core.Entities.Message", b =>
                {
                    b.HasOne("Core.Entities.Broadcast", "Broadcast")
                        .WithMany("Messages")
                        .HasForeignKey("BroadcastId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Broadcast");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Core.Entities.NormativeSportsman", b =>
                {
                    b.HasOne("Core.Entities.Normative", "Normative")
                        .WithMany("NormativeSportsmen")
                        .HasForeignKey("NormativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany("Normatives")
                        .HasForeignKey("SportsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Normative");

                    b.Navigation("Sportsman");
                });

            modelBuilder.Entity("Core.Entities.Personal", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithOne("Personal")
                        .HasForeignKey("Core.Entities.Personal", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.PersonalWorkout", b =>
                {
                    b.HasOne("Core.Entities.Personal", "Personal")
                        .WithMany("PersonalWorkouts")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany("PersonalWorkouts")
                        .HasForeignKey("SportsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Sportsman");
                });

            modelBuilder.Entity("Core.Entities.PlanTraining", b =>
                {
                    b.HasOne("Core.Entities.Personal", "Trainer")
                        .WithMany("PlanTrainings")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Core.Entities.PlayerEmbedding", b =>
                {
                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany()
                        .HasForeignKey("SportsmanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sportsman");
                });

            modelBuilder.Entity("Core.Entities.Sportsman", b =>
                {
                    b.HasOne("Core.Entities.Team", "Team")
                        .WithMany("Sportsmen")
                        .HasForeignKey("TeamId");

                    b.HasOne("Core.Entities.User", "User")
                        .WithOne("Sportsman")
                        .HasForeignKey("Core.Entities.Sportsman", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.SportsmanGroup", b =>
                {
                    b.HasOne("Core.Entities.Group", "Group")
                        .WithMany("SportsmanGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany("SportsmanGroups")
                        .HasForeignKey("SportsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Sportsman");
                });

            modelBuilder.Entity("Core.Entities.Team", b =>
                {
                    b.HasOne("Core.Entities.Personal", "Trainer")
                        .WithMany("Teams")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Core.Entities.Training", b =>
                {
                    b.HasOne("Core.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.PlanTraining", "PlanTraining")
                        .WithMany("Trainings")
                        .HasForeignKey("PlanTrainingId");

                    b.HasOne("Core.Entities.Personal", "Trainer")
                        .WithMany("Trainings")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("PlanTraining");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Core.Entities.TrainingMetrics", b =>
                {
                    b.HasOne("Core.Entities.Sportsman", "Sportsman")
                        .WithMany("TrainingMetrics")
                        .HasForeignKey("SportsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Training", "Training")
                        .WithMany("Metrics")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportsman");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Core.Entities.AiChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Core.Entities.Broadcast", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Core.Entities.Group", b =>
                {
                    b.Navigation("SportsmanGroups");
                });

            modelBuilder.Entity("Core.Entities.LocalNormative", b =>
                {
                    b.Navigation("LocalNormativeSportsmen");
                });

            modelBuilder.Entity("Core.Entities.Match", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Core.Entities.Normative", b =>
                {
                    b.Navigation("NormativeSportsmen");
                });

            modelBuilder.Entity("Core.Entities.Personal", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Images");

                    b.Navigation("PersonalWorkouts");

                    b.Navigation("PlanTrainings");

                    b.Navigation("Teams");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("Core.Entities.PlanTraining", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("Core.Entities.Sportsman", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LocalNormatives");

                    b.Navigation("Normatives");

                    b.Navigation("PersonalWorkouts");

                    b.Navigation("SportsmanGroups");

                    b.Navigation("TrainingMetrics");
                });

            modelBuilder.Entity("Core.Entities.Team", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Matches");

                    b.Navigation("Sportsmen");
                });

            modelBuilder.Entity("Core.Entities.Training", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Personal");

                    b.Navigation("Sportsman");
                });
#pragma warning restore 612, 618
        }
    }
}
